### ISSUE TITLE
new charts

### ISSUE THREAD

**Issue by manland** [manland/draw-my-project#14]
based on path and size file (pie chart)

**Comment by manland** [comment]
Help me @audreyn @undless @studiodev !!! Comment je rend ça mieux :sweat_smile: ? Qu'est-ce que vous imagineriez pour tout ça ?
- 1 : regroupé par type
- 2 : poids par type
- 3 et 4 : poids total

ps : vue le nombre de conseils 17 (et il manque par rapport au poids des controllers), skimbo est vraiment salement fait :stuck_out_tongue_closed_eyes: !!

![slection_225](https://f.cloud.github.com/assets/1492516/2199710/c1c6a1a8-98d7-11e3-8dcb-64293ef90675.png)
![slection_227](https://f.cloud.github.com/assets/1492516/2199711/c2046646-98d7-11e3-84fa-25b30a756b39.png)
![slection_226](https://f.cloud.github.com/assets/1492516/2199713/c2830dfc-98d7-11e3-92e7-869e367bebda.png)
![slection_228](https://f.cloud.github.com/assets/1492516/2199712/c204c4ec-98d7-11e3-91fd-c0dab6b9cb11.png)

**Comment by undless** [comment]
j'ai rien compris !!!

**Comment by manland** [comment]
https://twitter.com/jpwarren/status/431570440385871872/photo/1/large
