### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by manland** [manland/draw-my-project#15]
@undless wants font-size: 11px and font-family: sans-serif ! He will have it !

**Comment by undless** [comment]
hehehehe
i prefer 12px because... i prefer !

**Comment by manland** [comment]
Comme d'hab t'avais raison :gift_heart: 

![slection_224](https://f.cloud.github.com/assets/1492516/2190091/40fe5e4a-9822-11e3-89c1-8569690a9f05.png)
