### ISSUE TITLE
'grunt-draw-my-project' is not in the npm registry

### ISSUE THREAD

**Issue by julien-lafont** [manland/draw-my-project#39]
Hello

I have this error when I try to install your plugin:

```
$ npm install grunt-draw-my-project --save-dev
```

> npm WARN package.json client@0.0.0 No repository field.
> npm http GET https://registry.npmjs.org/grunt-draw-my-project
> npm http 404 https://registry.npmjs.org/grunt-draw-my-project
> npm ERR! 404 'grunt-draw-my-project' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, or http url, or git url.
> npm ERR! System Darwin 12.4.0
> npm ERR! command "/usr/local/Cellar/node/0.10.24/bin/node" "/usr/local/bin/npm" "install" "grunt-draw-my-project" "--save-dev"
> npm ERR! cwd /Users/xxxx/Travail/projets/xxxx/client
> npm ERR! node -v v0.10.24
> npm ERR! npm -v 1.3.21
> npm ERR! code E404
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /Users/xxx/Travail/projets/xxxx/client/npm-debug.log
> npm ERR! not ok code 0

I suppose the plugin is not yet published on public npm repos. Could you tell me how to fix that? (maybe publish in local, but how?).

Thanks :)

**Comment by manland** [comment]
Hey, I will publish draw_my_project, only when the 1.0.0 version will finished ;)

To test it just add this line in your package.json : 
`"grunt-draw-my-project": "git://github.com/manland/draw-my-project.git"`

And regularly, make a npm install to get latest version.

I will update the README page :D
