### ISSUE TITLE
Ignore the 'is never used' advice on directives and filters

### ISSUE THREAD

**Issue by julien-lafont** [manland/draw-my-project#40]
Most directives and filters are only used in templates, so it's generaly not an error that the element is not used (maybe a warn or something lighter)

**Comment by manland** [comment]
Linked to #28

**Comment by manland** [comment]
Done with gravity 0 (notserious) : https://github.com/manland/draw-my-project/blob/master/tasks/advices/NotUsed.js#L24

Can be desable with : options: {notUsed: false} (but desable all not used advices)

Soon more options
