### ISSUE TITLE
Distinguish services and resolved variables

### ISSUE THREAD

**Issue by julien-lafont** [manland/draw-my-project#41]
Currently, services (defined with `.service()`) and resolved variables (not related to a service but defined in the routing with `resolve: { groups: ['group', function(group) { return group.groups() }]}` are displayed in the same category.

The resolved variables should be separated or ignored.

**Comment by manland** [comment]
I think the 0.3.3 version fixes this issue https://github.com/manland/draw-my-project#033 with the new regexp : https://github.com/manland/draw-my-project/blob/master/tasks/parsers/angularjs.js#L4 

Could you confirm please ? (npm install to download the latest version ;))

Thx
