### ISSUE TITLE
Link source code

### ISSUE THREAD

**Issue by julien-lafont** [manland/draw-my-project#42]
Choose: 
- Display the source code of an element directly in the app
- Open the source code in a new tab
- At least, display the name of the file

**Comment by manland** [comment]
Work in progress... cc @studiodev @undless !

![slection_264](https://f.cloud.github.com/assets/1492516/2428437/63a68de8-ac48-11e3-9983-e52e98b87277.png)

**Comment by undless** [comment]
Ça claque !!!

**Comment by manland** [comment]
Work in progress 2 !

![slection_265](https://f.cloud.github.com/assets/1492516/2431919/9d485538-ad4a-11e3-89a4-493b283c19c4.png)

**Comment by julien-lafont** [comment]
Ca se passe comment, ça affiche à gauche le bon fichier ? (sur la bonne ligne s'il y a plusieurs éléments par fichiers ?)

Joli en tout cas :)

**Comment by manland** [comment]
Hahaha c'est même pas finit qu'il veut déjà des nouveaux trucs ^^

Je fignole et je push tu pourra voir par toi même ;) Mais en gros : 
- tu click sur un noeud : s'il y a du code ($scope, $http... n'a pas de code) tu le vois
- tu re-click sur le noeud ça cache
- tu click sur un autre noeud ça affiche l'autre (mais sans relacher le premier... je vais voir si je trouve mieux)
- plusieurs classes par noeud affiche tout le fichier (pas la ligne pour le moment)
- il n'y a pas les lignes des fichiers (pour le moment)

Bref work in progress... Et j'ai besoin de mon cogniticien préfér pour faire une petite passe ergonomique ^^ Pas facile de mettre autant de feature dans un si petit espace -__-'

**Comment by manland** [comment]
Bon je push même si c'est pas fini, ça fait une bonne base de discussion ;)

Vous pouvez tester en live là (lien caché pour le moment) http://manland.github.io/draw-my-project/showcases/angularApp/index.html#/ (sources from https://github.com/angular-app/angular-app) !

Ou mettre à jour la version de votre projet (d'ici 2 minutes) avec un petit `npm install` !

J'attends vos idées pour rendre ça plus ergonomique et plus pratique ^^

Bisous bisous
