### ISSUE TITLE
gestion des dépendances

### ISSUE THREAD

**Issue by gcharpentier** [manland/draw-my-project#51]
Est il obligatoire de déclarer les dépendance explicitement ? la wheel des dépendances n'en voie aucune sur mon projet.

Je ne sais pas si cela vient de là mais je crée le tableau par ngMin avant minification.

Cordialement

**Comment by manland** [comment]
Effectivement, je n'ai pas implémenté ce type d'injection. 

Je le fais ce soir, ça me permettra, en plus, de rajouter des erreurs si le dev à rajouter des dépendances sans les déclarer (par exemple app.factory(['$http', function($http, monAutreService...)]... ça ne passera pas à la minification) ! 

Merci pour ce retour ;)

**Comment by manland** [comment]
Par contre, si tu lances draw_my_project après minification ça devrait marcher, il suffit de mettre l'option https://github.com/manland/draw-my-project#optionsnbnodebyfile à -1 comme ici https://github.com/manland/draw-my-project/blob/master/Gruntfile.js#L214 (si tu es impatient ;))

**Comment by gcharpentier** [comment]
Oui mais ma minification fait aussi une concaténation de nombreux fichiers dont des plugins que je ne souhaite pas intégrer à l'analyse.

En tout cas merci pour ton travail c'est une excellente idée car je rencontre les mêmes problématique que toi avec mes collègues !! cela me sera très utile

De : Romain Maneschi [mailto:notifications@github.com]
Envoyé : mardi 4 mars 2014 09:57
À : manland/draw-my-project
Cc : CHARPENTIER Guillaume
Objet : Re: [draw-my-project] gestion des dépendances (#51)

Par contre, si tu lances draw_my_project après minification ça devrait marcher, il suffit de mettre l'option https://github.com/manland/draw-my-project#optionsnbnodebyfile à -1 comme ici https://github.com/manland/draw-my-project/blob/master/Gruntfile.js#L214 (si tu es impatient ;))

**Comment by manland** [comment]
Un petit npm install (pour download la dernière version) demain au taf et ça devrait rouler ;)

Merci pour tes encouragements, et n'hésites pas à ré-ouvrir si ça ne marche pas ;) De même si tu as d'autres pb/idées !

@+++
