### ISSUE TITLE
espace entre "fonction" et parenthèse des arguments

### ISSUE THREAD

**Issue by gcharpentier** [manland/draw-my-project#53]
si nous avons 'function (...)' à la place de 'function(...)' la regex du parser angular ne fonctionne plus.
Elle pourrait être : 
<code>
._?[^$](controller|provider|factory|service|value|constant|directive|config|run|filter)(['|"](.+?)['|"](.+?)function(_?(.*?))\
</code>

**Comment by manland** [comment]
Oups, merci ;)

J'ai testé pas mal de cas https://github.com/manland/draw-my-project/blob/master/test/fixtures/simple.js mais pas celui-là ! Ce soir ça sera fait !

**Comment by manland** [comment]
Salut @gcharpentier je me permet de te recontacter car on a transformé draw-my-project en saas pour une utilisation encore plus simplifié. 

Si tu es intéressé pour devenir alpha-testeur, inscrit toi sur la mailing list : http://kyu-project.co et je te rajouterais dans les alpha-testeurs ;)

Voici ce que ça donne dans la nouvelle version : http://kyu-project.co/appli/#/kyu/kyu

@très bientôt pour plus de code js !

**Comment by manland** [comment]
Resalut @gcharpentier je t'es bien ajouté comme alpha-testeur mais tu n'as pas validé ton compte (ni la newsletter). 

Tu as du recevoir 2 mails de kyu@kyu-project.co (peu tu vérifier tes spams ?) à l'intérieur il y a un lien de validation pour ton inscription (et pour la newsletter). Dans 2 ou 3 jours tes informations seront détruites de nos bases de données si tu ne les valide pas.

@+++
