### ISSUE TITLE
new skin

### ISSUE THREAD

**Issue by manland** [manland/draw-my-project#6]
Thanks to @undless <3 !!!!

![draw_my_project_1](https://f.cloud.github.com/assets/1492516/2173324/d49853ac-959f-11e3-9bc3-1fc85ccc50ee.png)
![draw_my_project_2](https://f.cloud.github.com/assets/1492516/2173325/d49fbd0e-959f-11e3-8fa0-655863dfef8e.png)

**Comment by undless** [comment]
\o/

**Comment by undless** [comment]
Des screenshots ! Des screenshots !

**Comment by manland** [comment]
Of course :tada: :gift:

![slection_220](https://f.cloud.github.com/assets/1492516/2181524/cc8cc8c6-9754-11e3-82d2-1dfd611ea45b.png)
![slection_221](https://f.cloud.github.com/assets/1492516/2181525/cc9582a4-9754-11e3-8265-b855426837ce.png)
![slection_222](https://f.cloud.github.com/assets/1492516/2181526/cc97bb5a-9754-11e3-8878-9820fdc137ab.png)
![slection_223](https://f.cloud.github.com/assets/1492516/2181527/cc97e2e2-9754-11e3-816a-6a0331d53d1c.png)

**Comment by julien-lafont** [comment]
Ah sympa l'idée :+1:  Ca rend super bien en plus !
